### ISSUE TITLE
running wavescan

### ISSUE THREAD

**Issue by chibchan** [porzione/wavescan#1]
trying this on an sfz
on kubuntu 20.04 I installed python 3.9.
pip install audiofile 
pip install Jinja2

#in terminal
wavescan -d /path/to/drum/folder --sfz > ~/Music/my.sfz
 I get this: 

Traceback (most recent call last):
  File "/home/alnone/Downloads/wavescan/wavescan", line 9, in <module>
    import libsfz
  File "/home/alnone/Downloads/wavescan/libsfz.py", line 5, in <module>
    from jinja2 import Template as J2, StrictUndefined as J2Undef
ModuleNotFoundError: No module named 'jinja2'

**Comment by porzione** [comment]
@chibchan  can you pls show output of `pip show jinja2` and `python -V`
